language: node_js

node_js:
  - stable

# 缓存，可以节省集成的时间
cache:
  npm: true
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

after_script:
  - cd ./public
  - git init
  - git config --global user.name "52admln"
  - git config --global user.email "ismrwang@gmail.com"
  - git add .
  - git commit -m "Automatically update from travis-ci"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master #GH_TOKEN是在Travis中配置token的名称

branches:
  only:
    - source

env:
  global:
    - GH_REF: github.com/52admln/blog.git
